baseURL = "https://progolang.com/"
languageCode = "en-us"
theme = "hyde"
title = "Pro Golang"

[params]
  description = "Go tutorials, tips and tricks."
  disqusShortname = ""
  googleAnalytics = ""
  layoutReverse = true
  theme = "hyde"
  themeColor = ""
  copyright = "© ProGolang.com 2018. All rights reserved."
[author]
  name = "Srinivasan Rangarajan"

[permalinks]
  posts = "/:slug/"
  page = "/:slug/"
