baseURL = "https://progolang.com/"
languageCode = "en-us"
theme = "hyde"
title = "Pro Golang"
disqusShortname = "progolang"
googleAnalytics = "UA-128175831-1"

[params]
  author = "Srinivasan Rangarajan"
  description = "Articles, Tips and Tutorials to become a Pro Go Programmer."
  dateformat = "Jan 2, 2006"
  layoutReverse = true
  themeColor = "theme-base-0f"
  copyright = "© ProGolang.com 2019. All rights reserved."
  highlightjs = true
  highlightjsstyle = "github"
  toc = "tocbot"

[author]
  name = "Srinivasan Rangarajan"

[permalinks]
  posts = "/:slug/"
  page = "/:slug/"
