baseURL = "https://progolang.netlify.com/"
languageCode = "en-us"
theme = "hyde"
title = "Pro Golang"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
